### ISSUE TITLE
Suggestion: Add pyproject.toml or setup.py

### ISSUE THREAD

**Issue by mscuthbert** [davidpanderson/Numula#2]
Just a suggestion:

To make it possible to install this as a normal python package, it'd probably be a good idea to add a pyproject.toml file (modern way) or setup.py (old way) to the project and move the source files into a "numula" subdirectory.  Then it's easily possible to track the project and get updates.

Good luck! -- Myke (music21)

**Comment by davidpanderson** [comment]
Thanks for the suggestion!
There's now a 'numula' package in PyPI, and I updated the docs accordingly.

This was pretty simple once I found the right docs.  But I waded through a morass of outdated and super obtuse stuff first.

**Comment by mscuthbert** [comment]
This was pretty simple once I found the right docs. But I waded through a morass of outdated and super obtuse stuff first.

Yes, definitely had that same experience.

**Comment by davidedelvento** [comment]
> This was pretty simple once I found the right docs

Perhaps link those "right docs" here for your future self and other poor souls finding themselves here with a similar problem?

**Comment by davidpanderson** [comment]
The one I found most useful:
https://packaging.python.org/en/latest/tutorials/packaging-projects/
