### ISSUE TITLE
Missing program example

### ISSUE THREAD

**Issue by davidedelvento** [davidpanderson/Numula#3]
From https://github.com/davidpanderson/Numula/wiki/Example:-appassionata the `op57.py` is a 404

**Comment by davidedelvento** [comment]
Same problem with https://github.com/davidpanderson/Numula/wiki/Example:-wasserklavier

**Comment by davidedelvento** [comment]
Same problem with https://github.com/davidpanderson/Numula/blob/main/nocturne.py in https://github.com/davidpanderson/Numula/wiki/Timing-control

**Comment by davidpanderson** [comment]
Oops!  All are fixed now.

**Comment by davidedelvento** [comment]
Very nice examples, thanks a lot!
For people landing here, the appropriate link for the nocturne (the most approachable example if you are starting from scratch) is https://github.com/davidpanderson/Numula/blob/main/examples/nocturne.py
